test:
	thriftgo -g go \
 		-p mongo:GoMod=test,PackagePrefix=test/biz/doc/model,IdlPath=video.thrift,IdlType=thrift,OutDir=/home/example,Name=mongodb,ModelDir=/home/example/biz/doc/model,DaoDir=/home/example/biz/doc/dao video.thrift
